// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DependencyIcon: typeof import('./../components/DependencyIcon.vue')['default']
    DependencyIconsCircle: typeof import('./../components/DependencyIconsCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
    TheNavigation: typeof import('./../components/TheNavigation.vue')['default']
  }
}
